### ISSUE TITLE
How to install it in MPV by Shinchiro on Windows 11?

### ISSUE THREAD

**Issue by rahaaatul** [guidocella/mpv-lrc#1]

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#files-on-windows

Create a `scripts` folder in which to place `lrc.lua`.

**Comment by rahaaatul** [comment]
> https://mpv.io/manual/master/#files-on-windows
> 
> Create a `scripts` folder in which to place `lrc.lua`.

I did that but I don't see no lyrics.

**Comment by guidocella** [comment]
This script provides keybindings to download lyrics, you don't magically see them by just installing it.

**Comment by rahaaatul** [comment]
> This script provides keybindings to download lyrics, you don't magically see them by just installing it.

But I have lyrics embedded inside the music I'm playing.

**Comment by rahaaatul** [comment]
Downloaded lyrics fixed it. 

Sorry, this is my first time using MPV. It's not user friendly at all. Everything is so different. Getting used to it.

**Comment by rahaaatul** [comment]
Is it possible to display like scrolling lyrics? like this:
![image](https://github.com/guidocella/mpv-lrc/assets/86149861/1a9a8b5d-e0c2-4d78-9c9b-d38f01e07dca)

**Comment by guidocella** [comment]
That's not implemented in mpv.
