### ISSUE TITLE
[feature request] search lyrics by media-title

### ISSUE THREAD

**Issue by Sx1Fl0NdqlkM6N4s2pswXKUI0k9FKTaOckLbNXu** [guidocella/mpv-lrc#2]
# Use-case:
mpv with youtube-dl --no-video / basic offline files without metadata.

# The issue:
- not sure if APIs provide generic search from media-title (i.e. "Rihanna - Only Girl") or if it would have to be further split apart.
- some automated sed for i.e. "(Official Video)", "(Audio)"
- user would likely still need to manually edit certain titles before search.

**Comment by guidocella** [comment]
Musixmatch requires the artist but this is possible with Netease which just takes a generic `keywords` parameter. I will add support tomorrow.

**Comment by guidocella** [comment]
Updated. I did not edit media-titles since NetEase seems to return the correct results even with file extensions and words in parentheses. You can manually change the title with `set force-media-title 'foo bar'` in the console.
